import { Button, LineEdit, VerticalBox } from "std-widgets.slint";

export component AppWindow inherits Window {
    
    in-out property<string> guess: 42;
    in-out property<string> message: "No result yet";
    
    callback compare-with-secret-number();

    VerticalBox {
    
        LineEdit {
            font-size: 14px;
            text: "\{root.guess}";
            edited(text) => {
                root.guess = text;
            }
        }
    
        Button {
            text: "Compare with secret number";
            clicked => {
                root.compare-with-secret-number();
            }
        }
    
        Text {
            text: "\{root.message}";
        }
        
    }
}
